name: CQ Check - Non-Builds
on: [push, pull_request]
jobs:
  lint:
     name: Lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Lint
         uses: github/super-linter@v3
         env:
           SUPPRESS_POSSUM: true
           LINTER_RULES_PATH: /
           VALIDATE_EDITORCONFIG: true
           EDITORCONFIG_FILE_NAME: .editorconfig
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
